### Everything the backend app has in AWS (its Kubernetes side lives in k8s-envs)

### Secrets (JWT_KEY), read by External Secrets and synced into a Kubernetes Secret.
### Named "<namespace>/<app>": only namespace prod's SecretStore role can read prod/*.
### The value is generated by Terraform but never stored in state or Git (ephemeral + write-only).
### Rotation: bump secret_string_wo_version and apply (invalidates all issued user tokens).
ephemeral "random_password" "jwt_key" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "backend" {
  name        = "prod/backend"
  description = "Backend app secrets (JWT_KEY), read by External Secrets"

  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "backend" {
  secret_id = aws_secretsmanager_secret.backend.id
  secret_string_wo = jsonencode({
    JWT_KEY = ephemeral.random_password.jwt_key.result
  })
  secret_string_wo_version = 1
}

### IAM role (IRSA, service account prod/hw-backend-prod): database login with IAM auth.
### May log in to the RDS instance only as app_user (created by the app-user migration).
### The resource is the instance's immutable resource ID (db-XXXX), not its name.
data "aws_iam_policy_document" "backend_rds_connect" {
  statement {
    actions   = ["rds-db:connect"]
    resources = ["arn:aws:rds-db:us-east-1:003636669641:dbuser:${module.rds.db_instance_resource_id}/app_user"]
  }
}

module "backend_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts"
  version = "~> 6.8"

  name            = "hw-eks-backend-prod"
  use_name_prefix = false
  policy_name     = "hw-eks-backend-prod"

  source_policy_documents = [data.aws_iam_policy_document.backend_rds_connect.json]

  oidc_providers = {
    eks_prod = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["prod:hw-backend-prod"]
    }
  }
}
