### Backend app secrets (JWT_KEY), read by External Secrets and synced into a Kubernetes Secret.
### Named "<namespace>/<app>": only namespace prod's SecretStore role can read prod/*.
### The value is generated by Terraform but never stored in state or Git (ephemeral + write-only).
### Rotation: bump secret_string_wo_version and apply (invalidates all issued user tokens).
ephemeral "random_password" "jwt_key" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "backend" {
  name        = "prod/backend"
  description = "Backend app secrets (JWT_KEY), read by External Secrets"

  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "backend" {
  secret_id = aws_secretsmanager_secret.backend.id
  secret_string_wo = jsonencode({
    JWT_KEY = ephemeral.random_password.jwt_key.result
  })
  secret_string_wo_version = 1
}
